version: '3.8'

services:
  streaming-app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      # Mount the media directory from the host to the container
      - /mnt/streaming:/app/media:ro
    environment:
      - NODE_ENV=production
      - MEDIA_PATH=/app/media
      - USE_LOCAL_FILES=true
    restart: unless-stopped
    networks:
      - streaming-network

  # Nginx for static file serving and reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/streaming:/usr/share/nginx/html/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - streaming-app
    restart: unless-stopped
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge