services:
  streaming:
    build: .
    container_name: streaming
    ports:
      - "7000:3001"
    volumes:
      - /mnt/streaming:/app/media:ro
    environment:
      - NODE_ENV=production
      - MEDIA_PATH=/app/media
      - USE_LOCAL_FILES=true
      - TMDB_API_KEY=${TMDB_API_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped